on:
  push:

jobs:
  test:
    name: Build and test the image

    strategy:
      matrix:
        variant:
          - dockerfile: Dockerfile
            mysql-version: "8.0"
          - dockerfile: Dockerfile.mysql57
            mysql-version: "5.7"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test the image
        uses: ./.github/actions/test
        with:
          mysql-version: ${{ matrix.variant.mysql-version }}
          dockerfile: ${{ matrix.variant.dockerfile }}
